version: '3'

tasks:
  default:
    desc: List the available tasks
    aliasses: ['help']
    cmds:
      - task -l

  install:
    desc: Run poetry install
    cmds:
      - poetry install

  test:
    desc: Run pytest
    cmds:
      - poetry run pytest
